#
## NGINX Ingress Controller Chart Values Overrides
#
controller:
  podAnnotations: {
    fluentbit.io/parser_stdout: nginx-ingress-controller
  }

  replicaCount: 3

  minAvailable: 3

  service:
    externalTrafficPolicy: Local